# nginx/nginx.conf
 
events {
	worker_connections 1024;
}
 
http {
	# Security headers на рівні Nginx
	add_header X-Frame-Options "DENY" always;
	add_header X-Content-Type-Options "nosniff" always;
	add_header Strict-Transport-Security
    	"max-age=31536000; includeSubDomains" always;
	add_header Referrer-Policy
    	"strict-origin-when-cross-origin" always;
 
	# Обмеження розміру тіла запиту
	client_max_body_size 1m;
 
	# Rate limiting zone
	limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
 
	# HTTPS сервер
	server {
    	listen 443 ssl;
    	server_name localhost;
 
    	ssl_certificate /etc/nginx/certs/selfsigned.crt;
    	ssl_certificate_key /etc/nginx/certs/selfsigned.key;
    	ssl_protocols TLSv1.2 TLSv1.3;
    	ssl_ciphers HIGH:!aNULL:!MD5;
    	ssl_prefer_server_ciphers on;
 
    	location / {
			proxy_pass http://api:8000;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto https;
		}
	}
 
	# Редирект HTTP → HTTPS
	server {
    	listen 80;
    	return 301 https://$host$request_uri;
	}
}
